fix(redirect): handle redirects explicitly
zkat/make-fetch-happen pull request #27
Opened 2017-05-22 13:58 UTC by nlkluth

Fixes #26

2017-05-22 18:16 UTC, zkat requested changes
This is really great! Thank you!

Only one small change request involving the errors themselves, but the lest looks great, is super thorough, and I love the tests. They covered pretty much anything I was keeping an eye out for. 👏🏼

2017-05-22 18:16 UTC, zkat commented on index.js
> +            throw new Error(`maximum redirect reached at: ${uri}`, 'max-redirect')
What does this second argument do? The convention so far has been to use a `code` property on error objects to have single codes that people can use.

2017-05-22 19:27 UTC, nlkluth commented on index.js
> +            throw new Error(`maximum redirect reached at: ${uri}`, 'max-redirect')
ah, this is my mistake. I'll get the change going thanks!

2017-05-22 22:07 UTC, zkat commented on index.js
> +            throw new Error(`maximum redirect reached at: ${uri}`, 'max-redirect')
nah. My main suggestion would be to use the convention I've been using for other libraries, so `E<COMECODE` in uppercase. Unix-style.

2017-05-22 22:49 UTC, nlkluth commented on index.js
> +            throw new Error(`maximum redirect reached at: ${uri}`, 'max-redirect')
Gave it a go - but happy to make changes :)

2017-05-22 23:41 UTC, zkat approved these changes

2017-05-22 23:42 UTC, zkat commented
💃

2017-05-22 23:42 UTC, merged

2017-05-23 00:08 UTC, zkat commented
This has been released as part of `2.4.4`. Thanks so much for this. It's awesome work, and *incredibly* helpful, and I really appreciate your time <3

2017-05-23 14:17 UTC, nlkluth commented
Thanks! 🙌